name: levitate
description: "A new Flutter project for travelling info."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  group_button: ^5.3.4
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.0+4
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.4
  customizable_counter: ^1.0.4
  otp_text_field: ^1.1.3
  badges: ^3.1.2
  liquid_pull_to_refresh: ^3.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  animated_hint_textfield: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.5.3
  dio: ^5.4.0
  flutter_polyline_points: ^2.0.0
  razorpay_flutter:
  slide_to_act: ^2.0.2
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  webview_flutter:
  confetti: ^0.7.0
  animate_do: ^3.3.4
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  checkout_screen_ui: ^1.0.0
  uuid: ^4.3.3
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy_Black.ttf

    - family: Gilroy Bold
      fonts:
        - asset: assets/fonts/Gilroy_Bold.ttf